@extends('web.layout.grids.2-1')
@section('seo_title', 'Datenschutzerklärung')
@section('seo_description', 'Datenschutzerklärung')
@section('section')
<section class="theme-light">
  <x-header title="Datenschutzerklärung" />
  <article>
    <h2>Datenschutzbestimmungen des SIPT Schweizer Institut für Psychotraumatologie (nachfolgend SIPT)</h2>
    <p>Das SIPT freut sich über Ihr Interesse an unserer Website. Der Schutz Ihrer Personendaten bei der Erhebung, Verarbeitung und Nutzung anlässlich Ihres Besuchs auf unserer Website ist uns ein wichtiges Anliegen. Deshalb betreiben wir die Web-Aktivitäten in Übereinstimmung mit den Gesetzen zum Datenschutz und zur Datensicherheit. Damit das SIPT ihre Dienstleistungen kundenorientiert und sachgemäss zur Verfügung stellen kann, ist sie darauf angewiesen, Nutzerdaten erheben und nutzen zu dürfen.</p>
    <p>Mit der Nutzung unserer Website www.psychotraumatologie-sipt.ch und/oder mit der Anmeldung oder Annahme unserer Offerte akzeptieren Sie die nachfolgend beschriebene Datenbearbeitung von das SIPT.</p>
    {{-- <h2>Erhebung und Verarbeitung von Daten</h2>
    <p>Das SIPT erfasst mit Hilfe üblicher Tools zur Datenerfassung, beispielsweise Cookies, Informationen über Besucher der Website. Jeder Zugriff auf die Website und jeder Abruf einer auf der Website hinterlegten Datei werden protokolliert. Die Speicherung dient internen systembezogenen und statistischen Zwecken. Protokolliert werden z.B. Name der abgerufenen Datei, Datum und Uhrzeit des Abrufs, übertragene Datenmenge, Meldung über erfolgreichen Abruf, Webbrowser und anfragende Domain. Zusätzlich werden die IP-Adressen der anfragenden Rechner protokolliert.</p>
    <h2>Welche Personendaten werden gesammelt</h2>
    <p>Personendaten werden nur erfasst, wenn Sie diese Angaben freiwillig machen, etwa wenn Sie sich für einen Kurs oder für ein mydigicomp-Konto registrieren. das SIPT fragt auch bei anderen Gelegenheiten nach persönlichen Informationen, z.B. wenn Sie an Gewinnspielen teilnehmen, Zusatzangebote nutzen oder wenn Sie das SIPT ein Anliegen mitteilen. das SIPT bewahrt ihre Korrespondenz auf.&nbsp;das SIPT speichert und verarbeitet persönliche Daten wie Vor - und Nachnamen,&nbsp; E-Mail Adressen, Zustell - und Rechnungsadressen und Telefonnummern.&nbsp;Ihre Daten werden solange aufbewahrt, wie sie dem Zweck der Leistungserfüllung dienen und unter Berücksichtigung von gesetzlichen Vorgaben wie namentlich Revisionspflichten.</p>
     --}}
    <h2>Erfassen von allgemeinen Daten und Informationen</h2>
    <p>Mit jedem Aufruf unserer Webseite werden eine Reihe von allgemeinen Daten und Informationen erfasst, auch solche, die einen Personenbezug haben. Diese Daten und Informationen
    werden in den Logfiles des Servers gespeichert. Erfasst werden können die verwendeten Browsertypen und Versionen, das vom zugreifenden System verwendete Betriebssystem, die
    Webseite, von welcher ein zugreifendes System auf unsere Website gelangt (sogenannte Referrer), die Unterwebseiten, welche über ein zugreifendes System auf unserer Webseite angesteuert werden, das Datum und die Uhrzeit eines Zugriffs auf die Website, eine Internet-Protokoll-Adresse (IP-Adresse), der Internet -Service-Provider des zugreifenden Systems und sonstige
    ähnliche Daten und Informationen, die der Gefahrenabwehr im Falle von Angriffen auf unsere IT-Infrastruktur dienen.</p>
    <h2>Personendaten</h2>
    <p>Personendaten sind Angaben, die sich auf bestimmte oder bestimmbare Personen beziehen. Die Bearbeitung umfasst jeden Umgang mit Personendaten, insbesondere das Aufbewahren,
    Bekanntgeben, Beschaffen, Erheben, Löschen, Speichern, Verändern, Vernichten und Verwenden.</p>
    
    <h2>Art, Zweck und Umfang der Bearbeitung</h2>
    <p>Mit der Nutzung dieser Webseite erklären Sie sich mit der Bearbeitung Ihrer Personendaten gemäss der vorliegenden Datenschutzerklärung einverstanden. Es werden nur solche Personendaten bearbeitet, die notwendig sind, um die Inhalte der Webseite korrekt darzustellen, die Inhalte der Webseite zu optimieren, die dauerhafte Funktionsfähigkeit der IT-Infrastruktur und der Technik der Webseite zu gewährleisten sowie um im Falle eines Cyberangriffs den Strafverfolgungsbehörden die notwendigen Informationen bereitzustellen. Die Personendaten werden für die Dauer bearbeitet, die für den eben erwähnten Zweck erforderlich ist. Personendaten, deren Bearbeitung nicht mehr erforderlich ist, werden anonymisiert oder gelöscht.</p>
    
    <h2>Datensicherheit und Haftung</h2>
    <p>Es werden angemessene sowie geeignete technische und organisatorische Massnahmen getroffen, um den Datenschutz und die Datensicherheit zu gewährleisten. Trotz solcher Massnahmen kann es bei der Bearbeitung von Personendaten im Internet zu Verletzungen des Datenschutzes kommen. Daher können wir keine absolute Datensicherheit gewährleisten und lehnen jegliche Haftung bei der Nutzung dieser Webseite ab (auch für verlinkte Webseiten).</p>
    
    
    <h2>Nutzung und Weitergabe von Personendaten</h2>
    <p>Das SIPT erhebt und bearbeitet Personendaten und teilweise Daten zu Ihrem Lernerfolg, um ihre Leistungen kunden-orientiert und sachgemäss zur Verfügung stellen zu können. das SIPT speichert Personendaten insbesondere zu Identifikations-, Abrechnungs- und Marketingzwecken. Marketingzwecke schliessen Ankündigungen von Events, Wettbewerben und Umfragen sowie Informationen über Dienstleistungen und Produkte der das SIPT und ihrer Partner ein.</p>
    <p>Ihre Personendaten und teilweise Daten zu Ihrem Lernerfolg werden an Dritte, insbesondere an Cloud-Anbieter weitergegeben, wenn dies zum Zwecke der Kurs- und Vertragsabwicklung, der Abrechnung, der Identifikation oder des kundenorientierten Marketings erforderlich ist.</p>
    <p>Für den Newsletter verwendet das SIPT die von Ihnen angegebene E-Mail-Adresse und benötigt hierfür Ihre Bestätigung, dass Sie mit dem Empfang einverstanden sind. Wenn Sie einen Kurs gebucht oder eine Dienstleistung gekauft haben, so erhalten Sie regelmässig weitere Empfehlungen von uns per E-Mail. Sollten Sie später keinen Newsletter oder keine werblichen Nachrichten mehr von uns erhalten wollen, können Sie jederzeit widersprechen.</p>
    <h2>Google Analytics </h2>
    <p>Diese Website benutzt Google Analytics. Google Analytics verwendet sog. «Cookies», Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch das Cookie erzeugten Informationen über Ihre Benutzung der Website wird an einen Server von Google in den USA übertragen und dort gespeichert. Ihre IP-Adresse wird von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt und dadurch anonymisiert. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers der Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben ist oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link (<a href="https://tools.google.com/dlpage/gaoptout?hl=de" target="_blank">https://tools.google.com/dlpage/gaoptout?hl=de</a>) verfügbare Browser-Plugin herunterladen und installieren. Alternativ klicken Sie bitte auf diesen Link, um die Erfassung durch Google Analytics zu verhindern. Dabei wird ein Opt-Out-Cookie auf Ihrem Gerät abgelegt, das die zukünftige Erfassung Ihrer Daten beim Besuch dieser Website verhindert. Löschen Sie Ihre Cookies in diesem Browser, müssen Sie erneut auf diesen Link klicken. Nähere Informationen hierzu finden Sie unter <a href="https://www.google.com/intl/de/analytics/privacyoverview.html" target="_blank">https://www.google.com/intl/de/analytics/privacyoverview.html</a>&nbsp;</p>
    <h2>Externe Links</h2>
    <p>Die Website der das SIPT enthält Verknüpfungen zu Websites Dritter. Der Link bedeutet nicht, dass das SIPT mit dem Inhalt der verlinkten Seiten einverstanden ist. Für die verlinkten Websites haftet ausschliesslich der jeweilige Betreiber. das SIPT überprüft die verlinkten Websites immer wieder auf Rechtmässigkeit und Aktualität. Es ist aber nicht möglich, die verlinkten Websites ständig zu überprüfen. Sobald das SIPT von veralteten oder fragwürdigen Inhalten auf den verlinkten Websites erfährt, wird sie den Link entfernen oder dem jeweiligen Betreiber die Unrechtmässigkeit melden.</p>
    <h2>Welche Inhalte sind urheberrechtlich geschützt</h2>
    <p>Die auf der Website der das SIPT veröffentlichten Inhalte unterliegen dem schweizerischen Urheberrecht und dürfen nicht ohne die schriftliche Einwilligung der das SIPT weder ganz noch teilweise kopiert, nachgeahmt oder anderweitig verwendet werden. Ohne Zustimmung erlaubt sind Downloads für den privaten Gebrauch oder im Zusammenhang mit einer Kursanmeldung.</p>
    <h2>Welche Haftung übernimmt das SIPT</h2>
    <p>Die Nutzung dieser Website erfolgt auf alleinige Gefahr des Nutzers. das SIPT schliesst jegliche Haftung aus, die aus oder im Zusammenhang mit dieser Website entstehen könnte.</p>
    <h2>Gerichtsstand</h2>
    <p>Diese Datenschutzbestimmungen unterliegen dem materiellen schweizerischen Recht. Ausschliesslicher Gerichtsstand ist Winterthur.</p>
    <h2>Welche Berichtigungs- und Auskunftsrechte stehen Ihnen zu</h2>
    <p>Jeder Nutzer kann seine Account-Informationen jederzeit unter Verwendung seines Logins und Passworts berichtigen. Für andere Berichtigungsanliegen oder für die Löschung des Accounts kann sich der Nutzer an&nbsp;<a href="mailto:rb@sipt.ch" target="_blank">rb@sipt.ch</a>&nbsp;wenden.</p>
    <p>Der Nutzer kann Auskunft verlangen, ob weitere Daten über ihn bearbeitet werden. Er kann diese Anfrage an&nbsp;<a href="mailto:rb@sipt.ch" target="_blank">rb@sipt.ch</a>&nbsp;senden. Zur eindeutigen Identifikation ist die Kopie der Identitätskarte oder des Passes beizulegen.</p>
  </article>
</section>
<x-quote size="is-sm" quote="Traumatherapie, Traumapädagogik und Beratung von traumatisierten Menschen: Beziehungsorientiert, unterstützend, fundiert, vernetzt. So arbeitet das SIPT. Im Zentrum steht dabei immer der Mensch und sein Trauma." author="Rosmarie Barwinski, Leiterin SIPT" />
@endsection